### ISSUE TITLE
Unable to run oracle code - Error - "ORA-01017: invalid credential or not authorized; logon denied"

### ISSUE THREAD

**Issue by DanielAdeniji** [onecompiler/bugs#12]
Output:

ERROR:
[ORA-01017.invalidcredentialornotauthorized.logondenied.txt](https://github.com/user-attachments/files/16661458/ORA-01017.invalidcredentialornotauthorized.logondenied.txt)
![ORA-01017 invalidcredentialornotauthorized logondenied](https://github.com/user-attachments/assets/f0da63a6-9428-4abd-abd9-24ac0b7939dc)
[ORA-01017.invalidcredentialornotauthorized.logondenied.txt](https://github.com/user-attachments/files/16661463/ORA-01017.invalidcredentialornotauthorized.logondenied.txt)
![ORA-01017 invalidcredentialornotauthorized logondenied](https://github.com/user-attachments/assets/0e33bd38-76ad-438c-a41b-29e29d2fe5b3)

Error: Command failed: timeout 7 sqlplus -S c##42pm33ag8_42pn32qry/p_42pm33ag8_42pn32qry@//:1521 @queries.sql

**Comment by onecompiler-ops** [comment]
We have fixed this
