### ISSUE TITLE
Some characters don't print right in Python...?

### ISSUE THREAD

**Issue by shrodi** [onecompiler/bugs#5]
I get weird behaviors at printing some characters using Python at onecompiler.com (as of 2024-04-26, 13:19 EDT).

So far I've got:
1. the letter [ x ] won't print
2. the French combination [ 'hui ] produces asterisks 

See examples at https://onecompiler.com/python/42bfc94rk

I've tried with different browsers, and no difference on my side.

Just in case the link above would show something else for someone else, here is a link to a screenshot of what I see on my side: https://i.imgur.com/roJvyAA.png

Any idea why...???

**Comment by onecompiler-ops** [comment]
Thanks for reporting, This is fixed now https://github.com/onecompiler/bugs/issues/5
